### ISSUE TITLE
Store scroll position and page

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#56]
To enable the user to get back to the correct page/scroll position, we need to store it in a global state (local storage or redux). This state will have to be read when a tab is loaded and set the page/scroll position accordingly.

Store analyses and orders page/scroll position separately.

**Comment by moedarrah** [comment]
- We are using Tabs for navigating between workflows, which is why clicking the back button always returns us to the Homepage. To enable the functionality of the back button, we need to replace Tabs with a Menu for navigation instead.

- ScrollRestoration has a few limitations:
1. This feature is exclusive to React Router versions 6 and above. There are a few deprecated features to consider when upgrading to V6. (useHistory, exact)
2. Nested routes are not supported, **so it's not suitable for our use case.**

- The scroll position can be saved either in local storage or within the global state.

**Comment by moedarrah** [comment]
Done!
